/**
 * English — the reference dictionary.
 *
 * Every other locale is typed against this one, so a missing or renamed key is
 * a compile error rather than a string that quietly falls back to English in
 * production. That matters more than it sounds: a half-translated government
 * page is read as a half-working one.
 *
 * What is here is the **interface**: navigation, labels, headings, statuses,
 * buttons, notices, empty states. What is deliberately NOT here is generated
 * content — an alert's reason, its evidence rows, the model's drivers. Those
 * are assembled by the detectors with figures interpolated into them, and
 * translating them honestly means having the detectors emit a message key and
 * parameters rather than a finished sentence. That is a real refactor across
 * every detector, and doing it badly would cost the explainability work more
 * than it gains. The limitation is stated in the UI and in the README rather
 * than hidden behind a language toggle that only half works.
 */

export const en = {
  locale: {
    name: "English",
    switchTo: "हिन्दी में देखें",
    partial:
      "The interface is available in Hindi. Alert reasons and evidence are generated by the detectors and remain in English.",
  },

  app: {
    name: "SatarkAI",
    tagline: "MPLADS monitoring & anomaly detection",
    ministry:
      "Ministry of Statistics and Programme Implementation · Data Informatics & Innovation Division",
  },

  nav: {
    dashboard: "Dashboard",
    alerts: "Alerts",
    forecast: "Early warning",
    works: "Works",
    audit: "Audit trail",
    notifications: "Notifications",
    signOut: "Sign out",
    skipToContent: "Skip to main content",
    main: "Main",
  },

  auth: {
    signIn: "Sign in",
    signingIn: "Signing in…",
    email: "Official email",
    password: "Password",
    demoAccounts: "Demonstration accounts",
    demoNote: "Each sees only its own jurisdiction. Password:",
    incorrect: "Email or password is incorrect.",
    demoFooter:
      "Demonstration build on synthetic data. Signals produced here are prompts for human review, never findings of fraud.",
    noJurisdiction:
      "This account has no jurisdiction assigned, so no scheme data can be shown. Contact the administrator to attach a state, district, constituency or agency to the account.",
  },

  notice: {
    syntheticTitle: "Synthetic demonstration data",
    synthetic:
      "every figure, work, Member of Parliament, agency and vendor shown here is generated for demonstration. No official MPLADS record is reproduced. Real state and district names are used for geographic realism only.",
    humanDecidesTitle: "AI flags, a human decides.",
    humanDecides:
      "Every signal on this platform is a risk-prioritised prompt for review, not a finding of fraud. Alerts carry the reason and the records behind them, and every action an officer takes is recorded in the audit trail.",
    coverageTitle: "Coverage:",
  },

  scope: {
    national: "All States & Union Territories",
    state: "State jurisdiction",
    district: "District jurisdiction",
    constituency: "Own constituency works",
    agency: "Assigned works",
    none: "No jurisdiction assigned",
  },

  hint: {
    scoreAtLeast80: "score 80 and above",
    noActionYet: "no action recorded yet",
    acrossFlagged: "across all flagged works",
    closedWithReason: "closed with a reason",
    sentUpward: "sent upward",
  },

  kpi: {
    works: "Works",
    recommended: "Recommended",
    sanctioned: "Sanctioned",
    released: "Released to vendors",
    completionRate: "Completion rate",
    pastOneYear: "Past one-year rule",
    awaitingMarking: "Awaiting completion marking",
    criticalAlerts: "Critical alerts",
    alertsInScope: "Alerts in scope",
    awaitingReview: "Awaiting review",
    valueFlagged: "Sanctioned value flagged",
    evidenceOnFile: "Evidence on file",
    decisionsRecorded: "Decisions recorded",
    explained: "Explained",
    escalated: "Escalated",
    officersInvolved: "Officers involved",
  },

  table: {
    work: "Work",
    workCode: "Work code",
    district: "District",
    state: "State",
    agency: "Agency",
    stage: "Stage",
    status: "Status",
    amount: "Amount",
    progress: "Progress",
    due: "Due",
    released: "Released",
    vendor: "Vendor",
    evidence: "Evidence",
    share: "Share",
    alerts: "Alerts",
    critical: "Critical",
    completed: "Completed",
    recommendedBy: "Recommended by",
    when: "When",
    officer: "Officer",
    decision: "Decision",
    reasonGiven: "Reason given",
    type: "Type",
    severity: "Severity",
    score: "Score",
    category: "Category",
    year: "Year",
    entitlement: "Entitlement",
    paid: "Paid",
    location: "Location",
  },

  workStatus: {
    RECOMMENDED: "Recommended by MP",
    SANCTIONED: "Sanctioned",
    IN_PROGRESS: "In progress",
    COMPLETED_UNMARKED: "Complete, not marked",
    COMPLETED: "Completed",
    CANCELLED: "Cancelled",
    notShownPublicly: "not shown as completed publicly",
  },

  alertType: {
    OVERDUE: "Overdue completion",
    PAYMENT_AHEAD: "Payment ahead of progress",
    COST_OVERRUN: "Cost overrun",
    ENTITLEMENT_BREACH: "Entitlement breach",
    MISSING_EVIDENCE: "Missing asset evidence",
    STUCK_UNMARKED: "Complete but not marked",
    DUPLICATE: "Possible duplicate work",
    FY_END_SPIKE: "Financial-year-end clustering",
    COST_OUTLIER: "Cost outlier vs peers",
    IA_CONCENTRATION: "Implementing agency concentration",
    ML_ANOMALY: "Multivariate anomaly",
  },

  alertState: {
    OPEN: "Awaiting review",
    ACKNOWLEDGED: "Acknowledged",
    CLARIFICATION_SOUGHT: "Clarification sought",
    EXPLAINED: "Explained",
    ESCALATED: "Escalated",
  },

  severity: {
    CRITICAL: "critical",
    HIGH: "high",
    MEDIUM: "medium",
    LOW: "low",
    INFO: "info",
  },

  role: {
    MINISTRY: "Ministry / Central Nodal Agency (MoSPI)",
    SNA: "State Nodal Authority",
    DISTRICT: "District Authority (NDA/IDA)",
    MP: "Hon'ble Member of Parliament",
    IA: "Implementing Agency",
  },

  review: {
    heading: "Record your decision",
    subtitle:
      "Nothing on this platform closes an alert by itself. Every state change carries the name of the person who made it.",
    action: "Action",
    note: "Note",
    required: "required",
    optional: "optional",
    record: "Record",
    recording: "Recording…",
    currently: "Currently",
    history: "Review history",
    noAction: "No action recorded yet. This alert is awaiting review.",
    readOnly:
      "Your role has read access to this alert. Action on oversight alerts rests with the district, state and ministry authorities.",
    footer:
      "Recording a decision does not accuse anyone of anything, and no penalty or report follows from it automatically. It records what an officer concluded, so that the next person to open this case can see it.",
  },

  common: {
    all: "All",
    filters: "Filters",
    filtersNote:
      "Filters narrow what you already have access to. They never widen it.",
    previous: "Previous",
    next: "Next",
    newer: "Newer",
    older: "Older",
    of: "of",
    page: "Page",
    showFigures: "Show figures",
    showChart: "Show chart",
    exportCsv: "Export this queue (CSV)",
    downloadPdf: "Download case note (PDF)",
    fullTimeline: "Full timeline",
    allWorks: "All works",
    alertQueue: "Alert queue",
    allForecasts: "All forecasts",
    markAllRead: "Mark all read",
    unread: "unread",
    source: "Source:",
    orderedByScore: "Ordered by Anomaly-Priority Score.",
    loading: "Loading…",
  },

  empty: {
    noAlertsTitle: "Nothing to review",
    noAlertsBody:
      "No alert in your jurisdiction matches these filters. That may mean the filters are too narrow, or that the rule engine has not been run since the data last changed.",
    noWorksTitle: "No works in your jurisdiction",
    noWorksBody:
      "Nothing has been recommended under MPLADS for the state, district, constituency or agency attached to this account.",
    noAuditTitle: "Nothing recorded yet",
    noAuditBody:
      "No officer has acted on an alert in your jurisdiction. Open an alert from the queue and record a decision to start the trail.",
    noNotificationsTitle: "Nothing yet",
    noNotificationsBody:
      "You will be notified when an officer acts on an alert in your jurisdiction, or escalates one to you.",
    noForecastTitle: "No forecasts available",
    noForecastBody:
      "Either no works in your jurisdiction are still running, or the model service has not been run. Forecasts need `npm run detect:ml`; the rest of the platform does not.",
  },

  error: {
    title: "Something went wrong on this page",
    body: "The error has been logged. You can try again, or go back to the dashboard. No data was changed by this failure.",
    retry: "Try again",
    backToDashboard: "Back to dashboard",
    notFoundTitle: "Record not available",
    notFoundBody:
      "This record either does not exist or falls outside the state, district, constituency or agency attached to your account. SatarkAI does not confirm the existence of records beyond your jurisdiction.",
  },
} as const;

/**
 * Widens the literal types `as const` produces, so a translation may hold any
 * string — while the KEYS stay exact. A locale file missing a key, or inventing
 * one, is a compile error; a locale file with different words is the point.
 */
type Translated<T> = {
  [K in keyof T]: T[K] extends string ? string : Translated<T[K]>;
};

export type Dictionary = Translated<typeof en>;
